const obj = {
  l_Main_page: "Asosiy sahifa",
  l_Services: "Xizmatlar",
  l_Select_department: "Bo'limni tanlang",
  l_Contact_information: "Bog'lanish uchun ma'lumot",
  l_About_app: "Dastur haqida",
  l_Language_selection: "Til tanlang",
  l_Version: "Versiya",
  l_All_rights_are_reserved: "Hamma huquqlar himoyalangan.",
  l_List_of_departments: "Bo'limlar ro'yxati",
  l_Contact_us: "Biz bilan bog'lanish",
  l_Contact_email_for_suggestions_and_questions:
    "Takliflar va savollar uchun elektron pochta manziliga murojaat qiling",
  l_Check_out_the_list_of_branches_nearest_you:
    "Sizga yaqin bo'lgan filiallar ro'yxatini ko'ring",
  l_Education: "Kurs",
  l_Sign_out: "Chiqish",
  l_Personal_information: "Shaxsiy ma'lumotlar",
  l_Add_new_recipient: "Yangi qabul qiluvchini qo'shish",
  l_Copied: "Nusxa olingan",
  l_Previous: "Oldingi",
  l_Now_open: "Ochiq",
  l_Edit: "Tahrirlash",
  l_Wallet: "Hamyon",
  l_Map: "Xarita",
  l_Guide: "Qoʻllanma",
  l_View_the_departments_on_the_map: "Bo'limlar ro'yxati",
  l_General_rules: "Umumiy qoidalar",
  l_BIN: "БИН",
  l_Disable_recipient: "Qabul qiluvchini o'chirish",
  l_Change_recipient: "Qabul qiluvchini o'zgartirish",
  l_CONTRACT: "SHARTNOMA",
  l_Delivery_to_me: "Menga yetkazing",
  l_Information_is_being_verified: "Ma'lumot tekshirilmoqda",
  l_Information_is_not_verified: "Ma'lumotlar tekshirilmagan",
  l_Do_you_want_to_delete_your_account:
    "Hisobingizni o'chirib tashlamoqchimisiz?",
  l_Delete_account_description:
    "Agar hisobingizni o'chirib tashlasangiz, bizning xizmatlarimizdan foydalana olmaysiz va ilovadagi barcha ma'lumotlaringiz o'chib ketadi. Xizmatlarimiz haqida savollaringiz bo'lsa, biz bilan bog'laning.",
  l_Cancel: "Bekor qilish",
  l_Continue: "Davom ettirish",
  l_Enter_your_phone_number_to_delete_an_account:
    "Akkauntni o'chirish uchun raqamni kiriting:",
  l_Phone: "Telefon",
  l_Delete_account: "Hisobni o'chirish",
  l_Wrong_number: "Noto'g'ri raqam",
  l_We_are_official_partners_of_Pinduoduo: "Biz Pinduoduo rasmiy sheriklariyiz",
  l_Courses_of_Pindodo: "Pindodo kurslari",
  l_Download_the_Pinduoduo_app: "Pinduoduo ilovasini yuklab oling",
  l_Branch_select_descr:
    "Bu buyurtma qilingan tovarlarni olib ketish uchun sizga eng yaqin bo'lgan filialning manzili. Siz uni istalgan vaqtda o'zgartirishingiz mumkin.",
  l_About_application_descr:
    "Jańa Post - mashhur Xitoy platformalaridan har xil turdagi posilkalarni tashiydigan ishonchli va tez yetkazib berish xizmati. Bizning mijozlar tashish va yetkazib berishning barcha bosqichlarini kuzatishi mumkin. Bu platformaning ustuvorligi mijozga yoʻnaltirilgan xizmat va noyob elektron tijorat tajribasi borligida. Ya’ni uydan chiqmasdan Xitoy platformalarida tovarlarni xarid qilish jarayonini sezilarli darajada osonlashtiradi.",
  l_Information_has_been_created: "Ma'lumot yaratildi",
  l_Information_verified: "Ma'lumotlar tasdiqlangan",
  l_Share_app: "Ilovani ulashish",
  l_Branch: "Filial",
  l_Go_to_home_page: "Bosh sahifaga o'ting",
  l_Profile_registered: "Profil ro'yxatga olingan",
  l_Your_information_complete: "Sizning ma'lumotlaringiz to'liq",
  l_Delivery_branch: "Yetkazib Berish Bo'limi",
  l_The_contract_agreed: "Shartnoma kelishilgan",
  l_In_order_to_pick_up_the_goods_that_you_ordered_earlier_you_must_choose_the_branch_closest_to_you:
    "Kelajakda buyurtma qilingan tovarlarni olish uchun sizga eng yaqin filialni tanlashingiz kerak.",
  l_Auth_steps_descr:
    "Jana Post - rasmiy logistika va yuridik ekspeditorlik kompaniyasi.  Biz orqali buyurtma berish uchun shaxsingizni tasdiqlovchi hujjat, yashash manzili va elektron imzoni taqdim etishingiz kerak.  Sizning shaxsiy ma'lumotlaringiz hech qayerda tarqatilmaydi, ular qonun hujjatlariga muvofiq himoyalanadi va saqlanadi.",
  l_Contract_agreement: "Shartnomaga roziligi",
  l_Auth_steps_descr_2:
    "Huquqlaringiz va manfaatlaringizni ta'minlash hamda amaldagi me'yoriy talablarga rioya qilish uchun “Umumiy qoidalar va shartlarni” diqqat bilan o'qib chiqishingizni tavsiya qilamiz.",
  l_Download_the_Pindodo_application: "Pindodo dasturini yuklab oling",
  l_Available: "Mavjud",
  l_Download: "Yuklab olish",
  l_No_internet: "Internet yo'q",
  l_Information: "Ma`lumot",
  l_Enter_personal_information: "Shaxsiy ma'lumotlaringizni kiriting",
  l_Personal_information_is_being_verified:
    "Shaxsiy ma'lumotlar tekshirilmoqda",
  l_Personal_information_has_not_been_verified:
    "Shaxsiy ma'lumotlar tekshirilmagan",
  l_Personal_information_verified: "Shaxsiy maʼlumotlar tasdiqlandi",
  l_View_the_list_of_departments: "Bo'limlar ro'yxatini ko'ring",
  l_Information_is_not_complete: "Ma'lumotlar to'liq emas",
  l_This_feature_requires_new_version:
    "Bu xususiyat yangi versiyani o'rnatishni talab qiladi, avval yangilang!",
  l_Agree: "Kelishuv",
  l_List_of_prohibited_items: "Taqiqlangan narsalar ro'yxati",
  l_Please_rate: "Iltimos, baho bering!",
  l_Next: "Keyingi",
  l_Submit: "Yuborish",
  l_Write_the_reason: "Sababini yozing",
  l_Thanks: "Rahmat!",
  l_Reyting: "Reyting",
  l_What_didnt_you_like: "Sizga nima yoqmadi?",
  l_Thanks_for_your_comment: "Izohingiz uchun rahmat!",
  l_Are_you_sure_you_want_logout:
    "Hisobingizdan chiqishni xohlayotganingizga aminmisiz?",
  l_Soon: "Yaqinda",
  l_Opening_soon: "Yaqinda ochiladi",
  l_The_first_1688_partners_in_KZ: "Qozog'istondagi birinchi 1688 hamkor",
  l_Tab_home_descr:
    "Logistika transport kompaniyasi Jańa Post endi 1688 Alibaba bilan bevosita hamkorlik qiladi!",
  l_Day: "Kun",
  l_What_can_we_improve_for_you: "Siz uchun nimani yaxshilashimiz mumkin??",
  l_Your_opinion: "Sizning fikringiz",
  l_Choose_a_reason: "Sababni tanlang",
  l_Open_your_own_branch: "O'z filialingizni oching",
  l_Update: "Yangilanish",
  l_New_version_is_ready: "Yangi versiya tayyor",
  l_Got_it: "Tushundim",
  l_Welcome: "Xush kelibsiz!",
  l_Fill_idcard_tips:
    "Jańa Post ilovasidan foydalanish uchun shaxsiy ma'lumotlaringizni kiriting. Siz taqdim etgan shaxsiy ma'lumotlar bojxona tekshiruvi uchun talab qilinadi va faqat bizda saqlanadi.",
  l_Statistics: "Statistika",
  l_Winner_determination: "G'olibni aniqlang",
  l_Winner: "G'olib",
  l_Track_code: "Trek kodi",
  l_Start: "Boshlash",
  l_Password_update: "Parolni yangilang",
  l_Settings: "Parametrlar",
  l_At_least_8_characters_are_required: "Kamida 8 ta belgi kerak",
  l_Enter_the_password_below_that_you_want_to_link_to_your_account:
    "Hisobingiz bilan bogʻlanmoqchi boʻlgan parolni quyida kiriting.",
  l_Password_quality: "Parol sifati",
  l_Dont_use_another_sites_password_or_something_too_obvious:
    "Boshqa sayt parolini yoki uy hayvoningizning ismi kabi juda aniq narsalarni ishlatmang.",
  l_Must_be_at_least_six_characters_one_letter_and_one_number:
    "Kamida oltita belgi, bitta harf va bitta raqam bo'lishi kerak",
  l_Password_has_been_updated: "Parol yangilandi",
  l_Minimum_password_length_The_new_password_must_contain_at_least_8_characters:
    "Minimal parol uzunligi: Yangi parol kamida 8 ta belgidan iborat bo'lishi kerak.",
  l_Password_rule_2:
    "Belgilar birikmasi: Parolda kamida bitta katta harf (A-Z), bitta kichik harf (a-z) va bitta raqam yoki maxsus belgi boʻlishi kerak.",
  l_Complete_all_requirements_to_change_your_password:
    "Parolni o'zgartirish uchun barcha talablarni bajaring",
  l_Your_bonus: "Bonuslaringiz",
  l_Get_1000_bonuses_for_each_referred_user:
    "Har bir tavsiya qilingan foydalanuvchi uchun 2.25 bonus oling",
  l_Terms_receiving_bonus: "Bonus olish shartlari",
  l_Install_app: "Ilovani o'rnating",
  l_Place_an_order: "Buyurtma bering",
  l_Share_and_get_bonus: "Ulashing va 1000₸ oling",
  l_Download_jp: "Jana Post yuklash",
  l_Place_an_order_through_a_jp_on_one_of_the_5_platforms:
    "5 platformaning biridan Jana Post orqali buyurtma bering",

  l_Register: "Ro'yxatdan o'tgan",
  l_Made_an_order: "Buyurtma berdi",
  l_Invite_friend_list: "Taklif qilingan do'stlar ro'yxati",
  l_Invite_list: "Takliflar ro'yxati",
  l_Bonus: "Bonus",
  l_The_data_is_updated_once_a_day: "Ma'lumotlar kuniga bir marta yangilanadi",
  l_The_order_must_be_placed_within_30_days:
    "Buyurtma 30 kun ichida berilishi kerak",
  l_ID_card_front: "ID kartaning oldingi ko'rinishi",
  l_ID_card_back: "ID kartaning orqa ko'rinishi",
  l_Draw_a_signature: "Imzoni chizish",
  l_Electronic_signature_to_confirm_your_personal_data:
    "Elektron imzo. Shaxsiy ma'lumotlaringizni tasdiqlash uchun siz elektron imzoyingizni kiritishingiz kerak",
  l_Please_fill_in_your_residential_address:
    "Yashash manzilingizni to'ldirishingizni so'raymiz",
  l_Select: "Tanlash",
  l_Other: "Boshqa",
  l_Choose_branch: "Filialni tanlash",
  l_Address: "Manzil",
  l_Name: "Ism",
  l_Delete: "O'chirish",
  l_Signature: "Imzo",
  l_Save: "Saqlash",
  l_I_Agree: "Roziman",
  l_From_China_to_the_branches: "Xitoydan filiallarga",
  l_No_data: "Ma'lumotlar yo'q",
  l_Choose_city_region: "Shahar/Mintaqani tanlang",
  l_More: "Batafsil",
  l_Share_with_your_friends_and_get_a_bonus:
    "Do'stlaringiz bilan bo'lishing va bonus oling!",
  l_View_on_the_map: "Xaritada ko'rish",
  l_ID_card: "Shaxsni tasdiqlovchi karta",
  l_Passport: "Pasport",
  l_Select_document_type: "Hujjat turini tanlang",
  l_List: "Ro'yxat",
  l_km: "km",
  l_Courier: "Kurer",
  l_tips_work_time:
    "Hurmatli mijoz! Istalgan savolingizga soat 9:00 dan 21:00 gacha javob olishingiz mumkin. Iltimos, ish vaqtida yozing!",
  l_Fill: "To'ldirish",
  l_Through_the_bonus_you_can_pay_for_the_logistics_cost_of_your_product:
    "Bonus orqali siz maxsulotingizning loyihalik qimmatini to'lashsiz.",
  l_Notice: "Diqqat!",
  l_Search_order: "Buyurtmani qidirish",
  l_Our_official_partners: "Bizning rasmiy hamkorlarimiz",
  l_Place_your_first_order_from_the_top_5_sites:
    "Birinchi buyurtmangizni 5 ta eng yaxshi saytga joylashtiring!",
  l_More_details: "Ko'proq o'qish",
  l_Available_offers: "Mavjud takliflar",
  l_On_delivery: "Yetkazib berishda",
  l_On_waiting: "Kutilganidek",
  l_Start_work: "Ishni boshlash",
  l_Finish_the_job: "Ishni tugat",
  l_Order: "Buyurtma",
  l_Confirmation_code: "Tasdiqlash kodi",
  l_Barcode: "Штрих-код",
  l_Verifucation_was_successful: "Tasdiqlash muvaffaqiyatli boʻldi",
  l_Make_a_call: "Qo'ng'iroq qilish",
  l_Resend_code: "Kodni qayta yuborish",
  l_Emergency_order: "Favqulodda buyurtma",
  l_Cause_of_emergency: "Favqulodda vaziyatning sababi",
  l_Basket: "Savat",
  l_Basket_number: "Savat raqami",
  l_Accept: "Qabul qiling",
  l_Reject: "Rad etish",
  l_Accepted: "Ruqsat etilgen",
  l_Rejected: "Rad etildi",
  l_Successfully_executed: "Muvaffaqiyatli bajarildi",
  l_You_take_full_responsibility_if_orders_are_lost:
    "Agar buyurtmalar yo'qolsa, siz to'liq javobgarlikni o'z zimmangizga olasiz",
  l_The_reason_for_the_emergency_should_not_be_empty:
    "Favqulodda vaziyatning sababi bo'sh bo'lmasligi kerak",
  l_Discontinued_deliveries: "To'xtatilgan yetkazib berish",
  l_Frozen_orders: "Muzlatilgan buyurtmalar",
  l_The_reason: "Chunki",
  l_No_more: "Boshqa emas",
  l_Receiving_orders: "Buyurtmalarni qabul qilish",
  l_Orders_to_be_returned_to_the_branch: "Buyurtmalar filialga qaytariladi",
  l_didnt_manage_to_delivery: "Men yetkazib berishga ulgurmadim",
  l_discount: "chegirma",
  l_Account_exchange: "Hisobni o'zgartirish",
  l_Add_Account: "Hisob qo'shing",
  l_Do_you_want_remove_the_registration_from_the_account_switch:
    "Ro'yxatdan o'tish yozuvini almashtirish hisobidan o'chirishni xohlaysizmi?",
  l_Free_course: "Bepul kurs",
  l_Sending_a_verification_code_to_the_client:
    "Mijozga tasdiqlash kodini yuborish",
  l_Branches: "Filiallar",
  l_Search: "Qidirish",
  l_Delivery_to_the_branch: "Filialga yetkazib berish",
  l_Delivery_to_home: "Uyga yetkazib berish",
  l_Within_1_working_day: "1 ish kuni ichida",
  l_Classes: "Darslar",
  l_Communication: "Aloqalar",
  l_Home_delivery: "Uyga etkazib berish",
  l_Marketplays: "Bozor",
  l_Bonuses: "Bonuslar",
  l_Add_new_account: "Yangi hisob qo'shish",
  l_Change_password: "Parolni o'zgartiring",
  l_Get_bonus_by_sharing_link_to_app:
    "Ilovaga havolani baham ko'ring va bonus oling",
  l_Share_link: "Havolani ulashing",
  l_Get_a_bonus: "bonus oling",
  l_Something_went_wrong: "Nimadir noto'g'ri ketdi",
  l_Your_branch: "Sizning filialingiz",
  l_Have_a_good_day_today: "Kuningiz xayrli o'tsin",
  l_Rate: "Baholash",
  l_Thanks_for_feedback: "Fikringiz uchun rahmat!",
  l_A_new_branch_was_opened: "Yangi filial ochildi",
  l_Yes_I_choose_this_branch: "Ha, men ushbu filialni tanlayman",
  l_Nearby_branches: "Yaqin filiallar",
  l_1688_desc:
    "1688 veb-saytining joriy kirish sahifasi tez orada yopiladi, chunki platforma ilovaga o'zgartirildi. Iltimos, ushbu sahifa orqali yangi mahsulotlarni xarid qilmang. Yangi mahsulotlarni sotib olish uchun «yangi 1688» tugmasini bosing va ilovaga o'ting va barcha buyurtmalaringizni o'sha erda joylashtiring. Tushunganingiz uchun rahmat!",
  l_Dear_customers: "Hurmatli mijozlar!",
  l_General_order: "Umumiy buyurtma",
  l_Invalid_order: "Noto'g'ri buyurtma",
  l_Estimated_income: "Prognoz qilingan daromad",
  l_Income_total: "Jami daromad",
  l_Level_1_client: "1-darajali mijoz",
  l_Accured_bonus: "Hisoblangan bonus",
  l_Your_invitation_code: "Sizning taklif kodingiz",
  l_Enter_the_invitation_code: "Taklif kodini kiriting",
  l_Operator: "Operator",
  l_Rating_the_app: "Ilovani baholash",
  l_No_messages: "Xabarlar yo'q",
  l_Exception_branch_text:
    "Agar tovarlarning holatida saralash markazi, bo'lim rafi ko'rsatilgan bo'lsa, siz eski bo'limdan tovarlarni olasiz.",
  l_Payment_check: "To'lovni tekshirish",
  l_User_name: "Foydalanuvchi nomi",
  l_User_password: "Foydalanuvchi paroli",
  l_Forgot_password: "Parolni unutdingizmi",
  l_Login: "Kirish",
  l_Sign_out: "Chiqish",
  l_EmailorPasswordisWrong: "Elektron pochta yoki parol noto'g'ri",
  l_User: "Foydalanuvchi",
  l_Payments: "To'lovlar",
  l_Promocodes: "Promokodlar",
  l_Messages: "Xabarlar",
  l_Consolidations: "Konsolidatsiyalar",
  l_Courier_Orders: "Kuryer buyurtmalari",
  l_Almaty: "Olmaota",
  l_Name: "Ism",
  l_Add: "Qo'shish",
  l_Action: "Harakat",
  l_Update: "Yangilanish",
  l_Submit: "Yuborish",
  l_Cancel: "Bekor qilish",
  l_Are_you_sure_delete_this_task:
    "Bu vazifani o'chirib tashlaganingizga ishonchingiz komilmi?",
  l_Yes: "Ha",
  l_No: "Yo'q",
  l_Tracking_number: "Kuzatuv raqami",
  l_Internal_Tracking_number: "Ichki kuzatuv raqami",
  l_Actual_Price: "Haqiqiy narx",
  l_Estimated_price: "Taxminiy narx",
  l_Actual_weight: "Haqiqiy vazn",
  l_kg: "kg",
  l_Estimated_weight: "Taxminiy vazn",
  l_Delivery_country: "Kelib chiqqan mamlakati",
  l_Delivery_type: "Etkazib berish turi",
  l_Address: "Manzil",
  l_Execution_status: "Bajarish holati",
  l_Cargo: "Yuk",
  l_Sign_up: "Ro'yxatdan o'tish",
  l_Next: "Davom etish",
  l_Verify_code: "Kodni tekshirish",
  l_Set_password: "Parolni o'rnatish",
  l_Confirm_password: "Parolni tasdiqlang",
  l_Get_SMS: "SMS olish",
  l_Get_the_verification_code_first: "Avval tasdiqlash kodini oling",
  l_Confirm_password_error: "Parolni tasdiqlash xatosi",
  l_Phone_number: "Telefon raqami",
  l_Password: "Parol",
  l_Wrong_password_format: "Noto'g'ri parol formati",
  l_Please_enter_phone_number: "Iltimos, telefon raqamini kiriting",
  l_Please_enter_sms: "SMSni kiriting",
  l_My_addresses: "Mening manzillarim",
  l_My_parcels: "Mening posilkalarim",
  l_Buy_instead_of_me: "Siz uchun sotib olamiz",
  l_Personal_data: "Shaxsiy ma'lumotlar",
  l_Update_password: "Parolni yangilash",
  l_Old_Password: "Eski parol",
  l_New_Password: "Yangi parol",
  l_Successed: "Muvaffaqiyatli",
  l_Personal_information: "Shaxsiy ma'lumotlar",
  l_User_list: "Foydalanuvchilar ro'yxati",
  l_Email: "Elektron pochta",
  l_Add_user: "Foydalanuvchi qo'shish",
  l_Full_name: "To'liq ism",
  l_IIN: "INS",
  l_ID_number: "ID raqami",
  l_Issuing_authority: "Emissiya qiluvchi organ",
  l_Issue_date: "Emissiya sanasi",
  l_Validity: "Validity",
  l_Delivery_address: "Etkazib berish manzili",
  l_Town: "Region-shahar/tuman",
  l_Street: "Ko'cha",
  l_House: "Uy",
  l_Postcode: "Pochta indeksi",
  l_Identity_card: "Identifikatsiya kartasi",
  l_Facial: "Yuz",
  l_Negotiable: "Orqaga",
  l_Draw_a_signature: "Imzoni chizish",
  l_Or_download_the_signed_contract: "Yoki imzolangan shartnomani yuklang",
  l_Note: "Eslatmalar",
  l_Precautions_for_uploading_pictures:
    "Biriktirilgan hujjat sifatli bo'lishi kerak. Rasm 1 MB dan oshmasligi kerak.",
  l_Click_or_drag_ile_to_this_area_to_upload:
    "Faylni yuklash yoki import qilish uchun shu yerni bosing",
  l_My_order: "Mening buyurtmam",
  l_Track_code: "Trek kodi",
  l_Recipient: "Qabul qiluvchi",
  l_Cargo_name: "Yuk nomi",
  l_Declared_price: "E'lon qilingan narx",
  l_Date: "Sana",
  l_Delivery_cost: "Etkazib berish narxi",
  l_Dispatch_country: "Dispatch Country",
  l_Delivery_method: "Etkazib berish usuli",
  l_Order: "Buyurtma",
  l_Recipient_data: "Qabul qiluvchi ma'lumotlari",
  l_Shipping_country: "Yuk tashish mamlakati",
  l_Transportation_method: "Transport usuli",
  l_Price: "Narx",
  l_Quantity: "Miqdor",
  l_Total_cost: "Jami xarajat",
  l_Category: "Kategoriya",
  l_Weapons_and_explosive_materials: "Qurol va portlovchi materiallar",
  l_Alcoholic_drinks: "Alkogolli ichimliklar",
  l_Sprays_and_aerosols: "Spreylar va aerozollar",
  l_Medicines_without_a_doctors_prescription:
    "Dori-darmonlar shifokorning retseptisiz",
  l_radioactive_elements: "Radioaktiv elementlar",
  l_Animals_and_plants: "Hayvonlar va o'simliklar",
  l_ALL_RIGHTS_RESERVED: "BARCHA HUQUQLAR HAQIDA",
  l_Contact: "Kontakt",
  l_About_us: "Biz haqimizda",
  l_The_shops: "Do'konlar",
  l_How_it_works: "Bu qanday ishlaydi?",
  l_Rates: "Tariflar",
  l_Frequently_asked_Questions: "Tez-tez so'raladigan savollar",
  l_Prohibited_Items: "Taqiqlangan narsalar",
  l_Privacy_Policy: "Maxfiylik siyosati",
  l_Weight: "Og'irligi",
  l_Declaration: "Deklaratsiya",
  l_Pay: "To'lov",
  l_Provinces: "Viloyatlar",
  l_Country: "Mamlakat",
  l_Full_address: "To'liq manzil",
  l_MY_ADDRESS_IN_CHINA_FOR_AUTO_DELIVERY: "Xitoydagi haydash manzili",
  l_Add_product: "Mahsulot qo'shish",
  l_Please_enter_quantity: "Miqdorni kiriting",
  l_The_maximum_number_is: "Maksimal raqam",
  l_China: "Xitoy",
  l_Auto_delivery: "Avtomatik yetkazib berish",
  l_To_avoid_problems_during_customs_clearance_please_enter_a_detailed_description_of_the_product_name_in_Russian:
    "Bojxona rasmiylashtiruvi paytida muammolarning oldini olish uchun rus tilida mahsulot nomining aniq tavsifini kiriting.",
  l_Later_confirm: "Keyinroq tasdiqlang",
  l_Confirm: "Tasdiqlash",
  l_Succeed: "Operatsiya muvaffaqiyatli o'tdi",
  l_Provide_a_link_to_the_product_we_will_buy_and_bring_it_for_you:
    "Mahsulotga havolani taqdim eting, biz uni sotib olamiz va siz uchun olib kelamiz!",
  l_Cargo_link: "Yuk havolasi",
  l_Additional_comment: "Qo'shimcha izoh",
  l_Are_you_willing_to_buy_if_the_price_fluctuates_up_to_7:
    "Agar narx 7% gacha o'zgarib tursa, sotib olishga tayyormisiz?",
  l_size: "Hajmi",
  l_Color: "Rang",
  l_Delivery_price: "Etkazib berish narxi",
  l_Promo_codes: "Promo kodlari",
  l_Whether_the_payment_is_completed: "Toʻlov tugallandimi?",
  l_Completed: "Bajarildi",
  l_Not_completed: "Tugallanmagan",
  l_Image_must_smaller_than_3MB: "Rasm 3MB dan kichik boʻlishi kerak!",
  l_Image_must_smaller_than_2MB: "Rasm 2MB dan kichik bo‘lishi kerak!",
  l_Image_format_error: "rasm formatida xatolik!",
  l_About: "Dastur haqida",
  l_Shops: "Do'konlar",
  l_How_to_work_with_China: "Xitoy bilan qanday ishlash kerak",
  l_OK: "OK",
  l_Quick_calculator: "Tezkor kalkulyator",
  l_Add_order: "Buyurtma qo'shish",
  l_Calculate_shipping_cost: "Yetkazib berish narxini hisoblang",
  l_Total_payment_amount: "To'lovning umumiy miqdori",
  l_Home: "Uy",
  l_one_click_copy: "Bir marta bosish bilan nusxalash",
  l_Email_format_error: "Elektron pochta formatida xatolik",
  l_Query_tracking: "So'rovlarni kuzatish",
  l_Contract_template: "Shartnoma shablon",
  l_File_format_error: "Fayl formati xatosi!",
  l_Back_home_page: "Uyga qaytish",
  l_Paid: "To'langan",
  l_Unpaid: "To'lanmagan",
  l_Payment_status: "To'lov holati",
  l_Search: "Qidirish",
  l_Ready_to_ship: "Yetkazib berishga tayyor",
  l_File: "Fayl",
  l_format_error: "Format xatosi",
  l_Description: "Ta'rif",
  l_Other: "Boshqa",
  l_Accept_PUBLIC_CONTRACT_and_AGREEMENT:
    "Ommaviy SHARTNOMA' va SHARTNOMAni qabul qiling'",
  l_Accept: "Qabul qilaman",
  l_PUBLIC_CONTRACT: "Jamoatchilik shartnomasi",
  l_And: "va",
  l_AGREEMENT: "KETISHMA",
  l_Not_found: "topilmadi",
  l_Order_tracking: "Buyurtmani kuzatish",
  l_All: "Hammasi",
  l_ID_card_information: "ID karta ma'lumotlari",
  l_Russian_language: "rus tili",
  l_If_total_price_exceeds_200_additional_tax:
    "Agar umumiy narx 200 AQSh dollaridan oshsa, qo'shimcha soliq undiriladi",
  l_Verification_failed_description: "Muvaffaqiyatsizlik sababi",
  l_New: "Yangi",
  l_Please_complete_the_information_first:
    "Iltimos, avval ma'lumotni to'ldiring",
  l_Loading: "Yuklanmoqda",
  l_Order_list: "Buyurtma roʻyxati",
  l_Add_track_code: "Track kodini qo'shish",
  l_Avia_delivery: "Avia yetkazib berish",
  l_Done: "Bajarildi",
  l_Upload_the_front_and_back_photos_of_your_ID_card:
    "ID kartangizning old va orqa fotosuratlarini yuklang",
  l_ID_card: "Shaxsni tasdiqlovchi karta",
  l_ID_card_front: "ID kartaning oldingi ko'rinishi",
  l_ID_card_back: "ID kartaning orqa ko'rinishi",
  l_In_order_to_deliver_goods_to_you_from_a_foreign_country_enter_the_information_of_the_identity_card:
    "Xorijiy davlatdan sizga tovarlarni yetkazib berish uchun shaxsingizni tasdiqlovchi hujjat ma'lumotlarini kiriting.",
  l_Enter_the_address_to_what_the_goods_should_be_delivered:
    "Tovar etkazib berilishi kerak bo'lgan manzilni kiriting",
  l_Signature: "Imzo",
  l_Save: "Saqlash",
  l_Edit: "Tahrirlash",
  l_Delete: "O'chirish",
  l_Order_documents_require_an_electronic_signature:
    "Buyurtma hujjatlari elektron imzoni talab qiladi.",
  l_It_is_necessary_to_make_payment:
    "Tovarni olish uchun to'lovni amalga oshirish kerak",
  l_Supplementation_of_the_declaration: "Deklaratsiyaga qo'shimcha",
  l_Deliver_goods_Kazakhstan_complete_the_declaration:
    "Qozog'istonga tovarlarni etkazib berish uchun deklaratsiyani to'ldirish kerak",
  l_Information: "Ma'lumot",
  l_Multiple_products_one_trackcode:
    "Ushbu bitta trek kodiga bir nechta mahsulotlarni qo'shishingiz mumkin",
  l_Goods_arrived_supplement_declaration:
    "Tovarlaringiz bizning omborimizga yetib keldi. Uni Qozog‘istonga yetkazish uchun deklaratsiyani to‘ldirish kerak. Tovaringizning nomi, hajmi va narxini ko‘rsatishingiz kerak",
  l_No_more: "Boshqa emas",
  l_No_data: "Ma'lumotlar yo'q",
  l_Previous: "Oldingi",
  l_Please_enter_price: "Narxni kiriting",
  l_Max_price_is: "maksimal narx",
  l_Min_price_is: "minimum narx",
  l_Max_quantity_is: "maksimal miqdor",
  l_Min_quantity_is: "minimiy miqdor",
  l_Load_more: "Ko'proq yuklash",
  l_Recipient_list: "Qabul qiluvchilar ro'yxati",
  l_Add_new_recipient: "Yangi qabul qiluvchini qo'shish",
  l_Our_branches: "Bizning filiallarimiz",
  l_Now_open: "Ochiq",
  l_Now_closed: "Yopiq",
  l_Sunday_off: "Yakshanba dam olish",
  l_From_China_to_the_branches: "Xitoydan filiallarga",
  l_Branch: "filial",
  l_Make_group_payment: "Paketlar guruhi uchun to'lov",
  l_You_can_pay_for_several_packages_at_once:
    "Siz bir vaqtning o'zida bir nechta paketlar uchun to'lashingiz mumkin",
  l_Select: "Tanlash",
  l_Group_pay: "Guruh to'lovi",
  l_Checking: "Ko'rib chiqilmoqda",
  l_Date_expected: "Kutilayotgan sana",
  l_Choose_branch: "Filialni tanlash",
  l_Cargo_price: "Tovar narxi",
  l_My_branch: "Mening filialim",
  l_In_shelf: "Javonda",
  l_Choose_payment_method: "To'lov usulini tanlang",
  l_Card: "Karta",
  l_Copied: "Nusxa olingan",
  l_Pay_by_kaspi: "Kaspi orqali to'lash",
  l_Payment_info: "To'lov ma'lumotlari",
  l_Order_number: "Buyurtma raqami",
  l_Quick_payment_in_the_kaspi_application: "Kaspi ilovasida tez to'lov",
  l_Please_check_the_card_limits: "Iltimos, karta limitlarini tekshiring",
  l_CONTRACT: "SHARTNOMA",
  l_I_Agree: "Roziman",
  l_Comment: "Sharh",
  l_Extra_information: "Qo'shimcha ma'lumot",
  l_Please_enter_delivery_address: "Iltimos, etkazib berish manzilini kiriting",
  l_Delivery_to_door: "Eshikka etkazib berish",
  l_By_filling_out_this_information_you_can_order_delivery_service:
    "Ushbu ma'lumotni to'ldirib, siz etkazib berish xizmatiga buyurtma berishingiz mumkin!",
  l_Make_request: "So'rov qiling",
  l_You_can_make_request_to_delivery_order_to_home:
    "eshikdan eshikka yetkazib berish xizmati",
  l_Created: "Yaratilgan",
  l_Prepared: "Tayyorlanish",
  l_Delivered: "Yuborilgan",
  l_In_delivery: "Yetkazib berish",
  l_Received: "Qabul qilindi",
  l_More_details: "Batafsil ma'lumot",
  l_Reject: "Rad etildi",
  l_Invalid_phone_number_format: "Telefon raqami formati noto'g'ri!",
  l_Delivery_to_me: "Menga yetkazing",
  l_Delivery_to_me_is_not_active:
    "'Menga yetkazing' xizmati sizning bo'linmangizga hali qo'shilmagan!",
  l_No_send: "Yuborilmadi",
  l_Enter_the_amount: "Miqdorni kiriting",
  l_Select_topup_method: "To'ldirish usulini tanlang",
  l_Replenishment: "To'ldirish",
  l_Top_up_wallet: "Hamyonni to'ldiring",
  l_My_wallet: "Mening hamyonim",
  l_Wallet_history: "Hamyon tarixi",
  l_Top_up_your_balance: "Balansingizni to'ldiring",
  l_Payment_for_cargo: "Yuk uchun to'lov",
  l_Transaction: "Tranzaksiya",
  l_My_bonus: "Mening bonuslarim",
  l_No_operations_for_selected_period:
    "Tanlangan davr uchun hech qanday tranzaksiya mavjud emas",
  l_Back: "Orqaga",
  l_Successfully_paid: "Muvaffaqiyatli to'langan",
  l_This_feature_requires_new_version:
    "Bu xususiyat yangi versiyani o'rnatishni talab qiladi, avval yangilang!",
  l_Not_enough_balance:
    "Sizda yetarli mablag‘ yo‘q! Birinchidan, hamyoningizni to'ldiring.",
  l_Payment_check: "To'lovni tekshirish",
  l_Translation_completed_successfully: "Tarjima muvaffaqiyatli yakunlandi!",
  l_Topped_up_via: "To'ldirish orqali",
  l_Service: "Xizmat",
  l_View_service_details: "Xizmat tafsilotlarini ko'rish",
  l_Hide_service_details: "Xizmat tafsilotlarini yashirish",
  l_Returned_to_account: "Hisobga pul qaytarildi",
  l_Transfer_between_accounts: "Hisoblar o'rtasida o'tkazish",
  l_Clear_wallet: "Hamyon tozalandi",
  l_Payment_number: "To'lov raqami",
  l_With_tenge: "Tengeda",
  l_Receipt: "Kvitansiya",
  l_Bonus_credited: "Bonus hisobga olinadi",
  l_Bonus_history: "Bonus tarixi",
  l_General: "Umumiy hisoblar",
  l_Bonus: "Bonus",
  l_All_information_is_protected:
    "Sizning ma'lumotlaringiz faqat buyurtmalarni kuzatish uchun ishlatiladi. Barcha ma'lumotlar himoyalangan va tarqatilmaydi.",
  l_Will_be_debited: "Kerak summa",
  l_Amount_to_be_paid: "To'lanishi summa",
  l_Required_information: "Talab qilingan malumot",
  Deliver_to_the_door_service_is_not_available:
    "Filialingizda Menga yetkazing xizmati mavjud emas",
  l_Cost_of_delivery_to_me: "Menga yetkazib berish narxi",
  l_Service_cost: "Xizmat narxi",
  l_WhatsApp: "WhatsApp ga yozing",
  l_Goods_coming_wait_accepted:
    "Sizning tovarlaringiz JAŃA POST xorijiy omboriga kelmoqda. Qabul qilinishini kuting.",
  l_Got_it: "Tushundim",
  l_Thanks_for_feedback: "Fikringiz uchun rahmat!",
  l_Share: "Ulashish",
  l_Is_this_helpful_for_you: "Javobni foydali deb topdingizmi?",
  l_Please_provide_reason: "Iltimos, sababini ko'rsating",
  l_Describe_suggestion_improve_answer:
    "Javobni yaxshilash uchun taklifni tavsiflang",
  l_I_did_not_get_full_answer_to_question: "Savolga to'liq javob olmadim",
  l_The_answer_was_not_helpful: "Javob yordam bermadi",
  l_My_suggestion: "Mening taklifim",
  l_FAQ: "Qo'llanma",
  l_Still_can_not_solve_problem: "Hali ham muammoni hal qila olmayapsizmi?",
  l_Statistics: "Statistika",
  l_Total_order_quantity: "Jami buyurtma miqdori",
  l_Total_order_weight: "Jami buyurtma og'irligi",
  l_Returned: "Qaytarildi",
  l_Transfer: "O'tkazish",
  l_Recipient_jpid: "JPID-ni tashkil etish",
  l_Message: "Xabar",
  l_Message_to_recipient: "Qabul qiluvchiga xabar",
  l_Change_recipient: "Qabul qiluvchini o'zgartirish",
  l_Enter_personal_information: "Shaxsiy ma'lumotlaringizni kiriting",
  l_Personal_information_is_being_verified:
    "Shaxsiy ma'lumotlar tekshirilmoqda",
  l_Personal_information_has_not_been_verified:
    "Shaxsiy ma'lumotlar tekshirilmagan",
  l_Personal_information_verified: "Shaxsiy maʼlumotlar tasdiqlandi",
  l_Required: "Majburiy maydon",
  l_Min_value: "Minimal qiymat",
  l_Max_value: "Maksimal qiymat",
  l_Not_enough_funds: "Mablag'lar yetarli emas",
  l_Specify_another_card: "Boshqa kartani ko'rsating",
  l_The_translation_failed: "Tarjima amalga oshmadi!",
  l_Please_try_again: "Yana bir bor urinib ko `ring",
  l_FAQ_long: "Tez-tez so'raladigan savollar",
  l_Balance: "Balans",
  l_Your_account_empty: "Sizning hisobingiz bo'sh!",
  l_To_receive_orders_through_application_topup_account:
    "Ilova orqali buyurtmalarni qabul qilish uchun hisobingizni to'ldiring",
  l_History: "Tarix",
  l_Invite: "Taklif",
  l_Buy: "Sotib olish",
  l_No_history: "Tarix yo'q",
  l_Filter: "Filtr",
  l_Period: "Davr",
  l_One: "Bir",
  l_Three: "Uch",
  l_Half: "Yarim",
  l_Half_year: "Yarim yil",
  l_Week: "Hafta",
  l_Year: "Yil",
  l_Month: "Oy",
  l_Months: "Oylar",
  l_Years: "Yillar",
  l_Order_information: "Buyurtma haqida ma'lumot",
  l_Order_delivered_department:
    "Sizning buyurtmangiz ushbu bo'limga yetkaziladi",
  l_No_messages: "Xabarlar yo'q",
  l_Rate: "Baholash",
  l_Passport: "Pasport",
  l_Select_document_type: "Hujjat turini tanlang",
  l_Upload_your_passport_photo: "Pasport rasmingizni yuklang",
  l_Nearby_branches: "Yaqin filiallar",
  l_Branch_successfully_updated: "Filial muvaffaqiyatli yangilandi",
  l_A_new_branch_was_opened: "Yangi filial ochildi",
  l_Exception_branch_text:
    "Agar tovarlarning holatida saralash markazi, bo'lim rafi ko'rsatilgan bo'lsa, siz eski bo'limdan tovarlarni olasiz.",
  l_Yes_I_choose_this_branch: "Ha, men ushbu filialni tanlayman",
  l_Free_delivery: "Bepul yetkazib berish",
  l_Home_delivery: "Uyga etkazib berish",
  l_Continue: "Davom ettirish",
  l_Fill_idcard_tips:
    "Введите свои личные данные, чтобы использовать приложение Jańa Post. Предоставленная вами личная информация необходима для таможенного досмотра и будет храниться только нами.",
  l_Electronic_signature_to_confirm_your_personal_data:
    "Elektron imzo. Shaxsiy ma'lumotlaringizni tasdiqlash uchun siz elektron imzoyingizni kiritishingiz kerak",
  l_Language_selection: "Til tanlang",
  l_Please_fill_in_your_residential_address:
    "Yashash manzilingizni to'ldirishingizni so'raymiz",
  l_Choose_city_region: "Shahar/Mintaqani tanlang",
  l_Map: "Xarita",
  l_List: "Ro'yxat",
  l_General_rules: "Umumiy qoidalar",
  l_View_on_the_map: "Xaritada ko'rish",
  l_Courier: "Kurer",
  l_On_delivery: "Yetkazib berishda",
  l_On_waiting: "Kutilganidek",
  l_Start_work: "Ishni boshlash",
  l_Finish_the_job: "Ishni tugat",
  l_Confirmation_code: "Tasdiqlash kodi",
  l_Barcode: "Штрих-код",
  l_Verifucation_was_successful: "Tasdiqlash muvaffaqiyatli boʻldi",
  l_Resend_code: "Kodni qayta yuborish",
  l_Emergency_order: "Favqulodda buyurtma",
  l_Cause_of_emergency: "Favqulodda vaziyatning sababi",
  l_Accepted: "Ruqsat etilgen",
  l_Rejected: "Rad etildi",
  l_Successfully_executed: "Muvaffaqiyatli bajarildi",
  l_You_take_full_responsibility_if_orders_are_lost:
    "Agar buyurtmalar yo'qolsa, siz to'liq javobgarlikni o'z zimmangizga olasiz",
  l_The_reason_for_the_emergency_should_not_be_empty:
    "Favqulodda vaziyatning sababi bo'sh bo'lmasligi kerak",
  l_The_reason: "Chunki",
  l_Receiving_orders: "Buyurtmalarni qabul qilish",
  l_Orders_to_be_returned_to_the_branch: "Buyurtmalar filialga qaytariladi",
  l_didnt_manage_to_delivery: "Men yetkazib berishga ulgurmadim",
  l_Please_rate: "Iltimos, baho bering!",
  l_Thanks_for_your_comment: "Izohingiz uchun rahmat!",
  l_What_can_we_improve_for_you: "Siz uchun nimani yaxshilashimiz mumkin??",
  l_Your_opinion: "Sizning fikringiz",
  l_Choose_a_reason: "Sababni tanlang",
  l_Sending_a_verification_code_to_the_client:
    "Mijozga tasdiqlash kodini yuborish",
  l_Rating_the_app: "Ilovani baholash",
};

const objKey = Array.from(new Set(Object.keys(obj))).reduce((acc, curr) => {
  return {
    [curr]: obj[curr],
    ...obj,
  };
}, {});

console.log(objKey);
