const langKeys = Object.keys({
        l_User_name: "User name",
        l_User_password: "User password",
        l_Forgot_password: "Forgot password",
        l_Login: "Log in",
        l_Sign_out: "Sign out",
        l_EmailorPasswordisWrong: "Email or passwordis wrong",
        l_User: "User",
        l_Payments: "Payments",
        l_Promocodes: "Promocodes",
        l_Messages: "Messages",
        l_Consolidations: "Consolidations",
        l_Courier_Orders: "Courier Orders",
        l_Almaty: "Almaty",
        l_Name: "Name",
        l_Add: "Add",
        l_Action: "Action",
        l_Update: "Update",
    
        l_Submit: "Submit",
        l_Cancel: "Cancel",
        l_Are_you_sure_delete_this_task: "Are you sure delete this task?",
        l_Yes: "Yes",
        l_No: "No",
        l_Tracking_number: "Tracking number",
        l_Internal_Tracking_number: "Internal Tracking number",
        l_Actual_Price: "Actual Price",
        l_Estimated_price: "Estimated price",
        l_Actual_weight: "Actual weight",
        l_kg: "kg",
        l_Estimated_weight: "Estimated weight",
        l_Delivery_country: "Country of origin",
        l_Delivery_type: "Delivery type",
        l_Address: "Address",
        l_Execution_status: "Execution status",
        l_Cargo: "Cargo",
        l_Sign_up: "Sign up",
        l_Next: "Next",
        l_Verify_code: "Verify code",
        l_Set_password: "Set password",
        l_Confirm_password: "Confirm password",
        l_Get_SMS: "Get SMS",
        l_Get_the_verification_code_first: "Get the verification code first",
        l_Confirm_password_error: "Confirm password error",
        l_Phone_number: "Phone number",
        l_Password: "Password",
        l_Wrong_password_format: "Wrong password format",
        l_Please_enter_phone_number: "Please enter phone number",
        l_Please_enter_sms: "Please enter SMS",
        l_My_addresses: "My addresses",
        l_My_parcels: "My parcels",
        l_Buy_instead_of_me: "Buy instead of me",
        l_Personal_data: "Personal data",
        l_Update_password: "Update password",
        l_Old_Password: "Old password",
        l_New_Password: "New password",
        l_Successed: "Successed",
        l_Personal_information: "Personal information",
        l_User_list: "User list",
        l_Email: "Email",
        l_Add_user: "Add user",
        l_Full_name: "Full name",
        l_IIN: "IIN",
        l_ID_number: "ID number",
        l_Issuing_authority: "Issuing authority",
        l_Issue_date: "Issue date",
        l_Validity: "Validity",
        l_Delivery_address: "Delivery address",
        l_Town: "City/Town",
        l_Street: "Street",
        l_House: "House",
        l_Postcode: "Postcode",
        l_Identity_card: "Identity card",
        l_Facial: "Facial",
        l_Negotiable: "Negotiable",
        l_Draw_a_signature: "Draw a signature",
        l_Or_download_the_signed_contract: "Or download the signed contract",
        l_Note: "Note",
        l_Precautions_for_uploading_pictures: "The attached document must be of good quality. The image file must not exceed 1 MB.",
        l_Click_or_drag_ile_to_this_area_to_upload: "Click or drag file to this area to upload",
        l_My_order: "My order",
        l_Track_code: "Track code",
        l_Recipient: "Recipient",
        l_Cargo_name: "Cargo name",
        l_Declared_price: "Declared price",
        l_Date: "Date",
        l_Delivery_cost: "Delivery cost",
        l_Dispatch_country: "Dispatch country",
        l_Delivery_method: "Delivery method",
        l_Order: "Order",
        l_Recipient_data: "Recipient data",
        l_Shipping_country: "Shipping country",
        l_Transportation_method: "Transportation method",
        l_Price: "Price",
        l_Quantity: "Quantity",
        l_Total_cost: "Total cost",
        l_Category: "Category",
        l_Weapons_and_explosive_materials: "Weapons and explosive materials",
        l_Alcoholic_drinks: "Alcoholic drinks",
        l_Sprays_and_aerosols: "Sprays and aerosols",
        l_Medicines_without_a_doctors_prescription: "Medicines without a doctor's prescription",
        l_radioactive_elements: "radioactive elements",
        l_Animals_and_plants: "Animals and plants",
        l_ALL_RIGHTS_RESERVED: "ALL RIGHTS RESERVED",
        l_Contact: "Contact",
        l_About_us: "About us",
        l_The_shops: "The shops",
        l_How_it_works: "How it works?",
        l_Rates: "Rates",
        l_Frequently_asked_Questions: "Frequently asked Questions",
        l_Prohibited_Items: "Prohibited Items",
        l_Privacy_Policy: "Privacy Policy",
        l_Weight: "Weight",
        l_Declaration: "Declaration",
        l_Pay: "Pay",
        l_Provinces: "Provinces",
        l_Country: "Country",
        l_Full_address: "Full address",
        l_MY_ADDRESS_IN_CHINA_FOR_AUTO_DELIVERY: "MY ADDRESS IN CHINA FOR AUTO DELIVERY",
        l_Add_product: "Add cargo",
        l_Please_enter_quantity: "Please enter quantity",
        l_The_maximum_number_is: "The maximum number is",
        l_China: "China",
        l_Auto_delivery: "Auto delivery",
        l_To_avoid_problems_during_customs_clearance_please_enter_a_detailed_description_of_the_product_name_in_Russian: "To avoid problems during customs clearance, please enter a detailed description of the product name in Russian.",
        l_Later_confirm: "Later Confirm",
        l_Confirm: "Confirm",
        l_Succeed: "Succeed",
        l_Provide_a_link_to_the_product_we_will_buy_and_bring_it_for_you: "Provide a link to the product, we will buy and bring it for you!",
        l_Cargo_link: "Cargo link",
        l_Additional_comment: "Additional comment",
        l_Are_you_willing_to_buy_if_the_price_fluctuates_up_to_7: "Are you willing to buy if the price fluctuates up to 7% ?",
        l_size: "Size",
        l_Color: "Color",
        l_Delivery_price: "Delivery price",
        l_Promo_codes: "Promo codes",
        l_Whether_the_payment_is_completed: "Whether the payment is completed?",
        l_Completed: "Completed",
        l_Not_completed: "Not completed",
        l_Image_must_smaller_than_3MB: "Image must smaller than 3MB!",
        l_Image_must_smaller_than_2MB: "Image must smaller than 2MB!",
        l_Image_format_error: "image format error!",
        l_About: "About",
        l_Shops: "Shops",
        l_How_to_work_with_China: "How to work with China",
        l_OK: "OK",
        l_Quick_calculator: "Quick calculator",
        l_Add_order: "Add order",
        l_Calculate_shipping_cost: "Calculate shipping cost",
        l_Total_payment_amount: "Total payment amount",
        l_Home: "Home",
        l_one_click_copy: "One-click copy",
        l_Email_format_error: "Email format error",
        l_Query_tracking: "Query tracking",
        l_Contract_template: "Contract template",
        l_File_format_error: "File format error!",
        l_Back_home_page: "Back Home",
        l_Paid: "Paid",
        l_Unpaid: "Unpaid",
        l_Payment_status: "Payment status",
        l_Search: "Search",
        l_Ready_to_ship: "Ready to ship",
        l_File: "File",
        l_format_error: "Format error",
        l_Description: "Description",
        l_Other: "Other",
        l_Accept_PUBLIC_CONTRACT_and_AGREEMENT: 'Accept "PUBLIC CONTRACT" and "AGREEMENT"',
        l_Accept: "Accept",
        l_PUBLIC_CONTRACT: "PUBLIC CONTRACT",
        l_And: "and",
        l_AGREEMENT: "AGREEMENT",
        l_Not_found: "Not found",
        l_Order_tracking: "Order tracking",
        l_All: "All",
        l_ID_card_information: "ID card information",
        l_Russian_language: "Russian language",
        l_If_total_price_exceeds_200_additional_tax: "If the total price exceeds 200 USD, additional tax will be charged",
        l_Verification_failed_description: "Failure reason",
        l_New: "New",
        l_Please_complete_the_information_first: "Please fill the information first",
        l_Loading: "Loading",
    
        l_Order_list: "Order list",
        l_Add_track_code: "Add Track Code",
        l_Avia_delivery: "Avia delivery",
        l_Done: "Done",
        l_Upload_the_front_and_back_photos_of_your_ID_card: "Upload the front and back photos of your ID card",
        l_ID_card: "Identity Card",
        l_ID_card_front: "The front view of the ID card",
        l_ID_card_back: "The back view of the ID card",
        l_In_order_to_deliver_goods_to_you_from_a_foreign_country_enter_the_information_of_the_identity_card: "In order to deliver goods to you from a foreign country, enter the information of the identity card.",
        l_Enter_the_address_to_what_the_goods_should_be_delivered: "Enter the address to which the goods should be delivered",
        l_Signature: "Signature",
        l_Save: "Save",
    
        l_Edit: "Edit",
        l_Delete: "Delete",
        l_Order_documents_require_an_electronic_signature: "Order documents require an electronic signature.",
    
        l_It_is_necessary_to_make_payment: "It is necessary to make a payment to get the goods",
        l_Supplementation_of_the_declaration: "Supplementation of the declaration",
        l_Deliver_goods_Kazakhstan_complete_the_declaration: "In order to deliver goods to Kazakhstan, it is necessary to complete the declaration",
        l_Information: "Information",
        l_Multiple_products_one_trackcode: "You can add multiple products to this one track code",
        l_Goods_arrived_supplement_declaration: "Your goods have arrived at our warehouse. In order to deliver it to Kazakhstan, it is necessary to supplement the declaration. You have to include the name, size, and price of your goods",
        l_No_more: "No more",
        l_No_data: "No data",
        l_Previous: "Previous",
    
        l_Please_enter_price: "Please enter price",
        l_Max_price_is: "max price is",
        l_Min_price_is: "min price is",
        l_Max_quantity_is: "max quantity is",
        l_Min_quantity_is: "min quantity is",
        l_Load_more: "Load more",
        l_Recipient_list: "Recipient List",
        l_Add_new_recipient: "Add new recipient",
    
        l_Our_branches: "Our branches",
        l_Now_open: "Open",
        l_Now_closed: "Closed",
        l_Sunday_off: "Sunday off",
        l_From_China_to_the_branches: "From China to the branches",
        l_Branch: "Branch",
    
        l_Make_group_payment: "Pay for the group of package",
        l_You_can_pay_for_several_packages_at_once: "You can pay for several packages at a time",
        l_Select: "Select",
        l_Group_pay: "Group pay",
    
        l_Checking: "Under review",
        l_Date_expected: "Date expected",
        l_Choose_branch: "Choose a branch",
    
        l_Cargo_price: "Goods price",
    
        l_My_branch: "My branch",
        l_In_shelf: "In shelf",
        l_Choose_payment_method: "Choose payment method",
        l_Card: "Card",
        l_Copied: "Copied",
        l_Pay_by_kaspi: "Pay by Kaspi",
        l_Payment_info: "Payment info",
        l_Order_number: "Order number",
        l_Quick_payment_in_the_kaspi_application: "Quick payment in the Kaspi application",
        l_Please_check_the_card_limits: "Please check the card limits",
        l_CONTRACT: "CONTRACT",
        l_I_Agree: "I agree",
        l_Comment: "Comment",
        l_Extra_information: "Extra information",
        l_Please_enter_delivery_address: "Please enter delivery address",
        l_Delivery_to_door: "Delivery to the door",
        l_By_filling_out_this_information_you_can_order_delivery_service: "By filling out this information, you can order a delivery service!",
        l_Make_request: "Make a request",
        l_You_can_make_request_to_delivery_order_to_home: "Door-to-door delivery service",
        l_Created: "Created",
        l_Prepared: "Preparing",
        l_Delivered: "Sent",
        l_In_delivery: "In delivery",
        l_Received: "Received",
        l_More_details: "More details",
        l_Reject: "Rejected",
        l_Invalid_phone_number_format: "The phone number is not in the correct format!",
        l_Delivery_to_me: "Delivery to me",
        l_Delivery_to_me_is_not_active: "So far, the 'Delivery to me' service has not been activated in your branch!",
        l_No_send: "Not sent",
        l_Enter_the_amount: "Enter the amount",
        l_Select_topup_method: "Select a top up method",
        l_Replenishment: "Top up",
        l_Top_up_wallet: "Top up wallet",
        l_My_wallet: "My wallet",
        l_Wallet_history: "Wallet history",
        l_Top_up_your_balance: "Top up your balance",
        l_Payment_for_cargo: "Payment for cargo",
        l_Transaction: "Transaction",
        l_My_bonus: "My bonus",
        l_No_operations_for_selected_period: "No operations for the selected period",
        l_Back: "Back",
        l_Successfully_paid: "Successfully paid",
        l_This_feature_requires_new_version: "This feature requires a new version to be installed, please update first!",
        l_Not_enough_balance: "You don't have enough funds! First, top up your wallet.",
        l_Payment_check: "Payment check",
        l_Translation_completed_successfully: "Translation completed successfully!",
        l_Topped_up_via: "Topped up via",
        l_Service: "Service",
        l_View_service_details: "View service details",
        l_Hide_service_details: "Hide service details",
        l_Returned_to_account: "Money returned to account",
        l_Transfer_between_accounts: "Transfer between accounts",
        l_Clear_wallet: "Wallet cleared",
        l_Payment_number: "Payment number",
        l_With_tenge: "With tenge",
        l_Receipt: "Receipt",
        l_Bonus_credited: "Bonus credited",
        l_Bonus_history: "Bonus history",
        l_General: "General",
        l_Bonus: "Bonus",
        l_All_information_is_protected: "Your information will only be used to track orders. All information is protected and will not be distributed.",
        l_Will_be_debited: "Will be debited",
        l_Amount_to_be_paid: "Amount to be paid",
        l_Required_information: "Required information",
        Deliver_to_the_door_service_is_not_available: "Delivery to me service is not available at your branch",
        l_Cost_of_delivery_to_me: "Cost of delivery to me",
        l_Service_cost: "Service cost",
        l_WhatsApp: "Write to WhatsApp",
        l_Goods_coming_wait_accepted: "Your goods are coming to JAŃA POST foreign warehouse. Wait for it to be accepted.",
        l_Got_it: "Got it",
        l_Thanks_for_feedback: "Thank you for your feedback!",
        l_Share: "Share",
        l_Is_this_helpful_for_you: "Did you find the answer helpful?",
        l_Please_provide_reason: "Please provide a reason",
        l_Describe_suggestion_improve_answer: "Describe a suggestion to improve the answer",
        l_I_did_not_get_full_answer_to_question: "I didn't get a full answer to the question",
        l_The_answer_was_not_helpful: "The answer was not helpful",
        l_My_suggestion: "My suggestion",
        l_FAQ: "Guide",
        l_Still_can_not_solve_problem: "Still can't solve the problem?",
        l_Statistics: "Statistics",
        l_Total_order_quantity: "Total order quantity",
        l_Total_order_weight: "Total order weight",
        l_Returned: "Returned",
        l_Transfer: "Transfer",
        l_Recipient_jpid: "Recipient's JPID",
        l_Message: "Message",
        l_Message_to_recipient: "Message to the recipient",
        l_Change_recipient: "Change recipient",
        l_Enter_personal_information: "Enter personal information",
        l_Personal_information_is_being_verified: "Personal information is being verified",
        l_Personal_information_has_not_been_verified: "Personal information has not been verified",
        l_Personal_information_verified: "Personal information verified",
        l_Required: "Required field",
        l_Min_value: "Min value",
        l_Max_value: "Max value",
        l_Not_enough_funds: "Not enough funds",
        l_Specify_another_card: "Specify another card",
        l_The_translation_failed: "The translation failed!",
        l_Please_try_again: "Please try again",
        l_FAQ_long: "Frequently asked questions",
        l_Balance: "Balance",
        l_Your_account_empty: "Your account is empty!",
        l_To_receive_orders_through_application_topup_account: "To receive orders through the application, top up your account",
        l_History: "History",
        l_Invite: "Invite",
        l_Buy: "Buy",
        l_No_history: "No history",
        l_Filter: "Filter",
        l_Period: "Period",
        l_One: "One",
        l_Three: "Three",
        l_Half: "Half",
        l_Half_year: "Half a year",
        l_Week: "Week",
        l_Year: "Year",
        l_Month: "Month",
        l_Years: "Years",
        l_Months: "Months",
        l_Order_information: "Order information",
        l_Order_delivered_department: "Your order will be delivered to this department",
        l_No_messages: "No messages",
        l_Rate: "Rate",
        l_Passport: "Passport",
        l_Select_document_type: "Select document type",
        l_Upload_your_passport_photo: "Upload your passport photo",
        l_Nearby_branches: "Nearby branches",
        l_Branch_successfully_updated: "Branch successfully updated",
        l_A_new_branch_was_opened: "A new branch was opened",
        l_Exception_branch_text: "If the status of the goods shows the sorting center, department shelf, you will receive the goods from the old department. You can receive only the goods that have not reached the sorting center from the newly selected department.",
        l_Yes_I_choose_this_branch: "Yes, I choose this branch ",
        l_Free_delivery: "Free delivery",
        l_Home_delivery: "Home delivery",
        l_Continue: "Continue",
        l_Fill_idcard_tips: "Enter your personal data to use the Jańa Post App. The personal information provided by you is required for customs inspection and will only be stored by us.",
        l_Electronic_signature_to_confirm_your_personal_data: "Electronic Signature. To confirm your personal data, you need to enter your electronic signature",
        l_Language_selection: "Language selection",
        l_Please_fill_in_your_residential_address: "Please fill in your residential address",
        l_Choose_city_region: "Select a city/region",
        l_Map: "Map",
        l_List: "List",
        l_General_rules: "General rules",
        l_View_on_the_map: "View on the map",
        l_Courier: "Courier",
        l_On_delivery: "On delivery",
        l_On_waiting: "On waiting",
        l_Start_work: "Start work",
        l_Finish_the_job: "Finish the job",
        l_Confirmation_code: "Confirmation code",
        l_Barcode: "Barcode",
        l_Verifucation_was_successful: "Verification was successful",
        l_Resend_code: "Resend code",
        l_Emergency_order: "Emergency order",
        l_Cause_of_emergency: "Cause of emergency",
        l_Accepted: "Accepted",
        l_Rejected: "Rejected",
        l_Successfully_executed: "Successfully executed",
        l_You_take_full_responsibility_if_orders_are_lost: "You take full responsibility if orders are lost",
        l_The_reason_for_the_emergency_should_not_be_empty: "The reason for the emergency should not be empty",
        l_The_reason: "The reason",
        l_Receiving_orders: "Receiving orders",
        l_Orders_to_be_returned_to_the_branch: "Orders to be returned to the branch",
        l_didnt_manage_to_delivery: "I didn't manage to deliver",
        l_Please_rate: "Please rate!",
        l_Thanks_for_your_comment: "Thanks for your comment!",
        l_What_can_we_improve_for_you: "What can we improve for you?",
        l_Your_opinion: "Your opinion",
        l_Choose_a_reason: "Choose a reason",
        l_Sending_a_verification_code_to_the_client: "Sending a verification code to the client",
        l_Rating_the_app: "Rating the app",
        "l_No_internet": "No internet",
        l_Add_a_card: "Add a card",
        l_We_do_not_store_card_data_Freedom_guarantees_security: "We do not store card data. Freedom guarantees security",
        l_Payment_in_process: "Payment in process",
        l_The_amount_will_credited_to_card_within_minutes: "The amount will be credited to the card within a few minutes",
        l_Delete_card_details: "Delete card details?",
        l_This_bank_card_will_no_displayed_cards_available_payment: "This bank card will no longer be displayed in the list of cards available for payment.",
})

const langTg = ["Номи истифодабаранда",  "Рамз",  "Барқарор кардани рамз",  "Ворид шудан",  "Баромадан",  "Почтаи электронӣ е рамз нодуруст аст",  "Истифодабаранда",  "Пардохтҳо",  "Рамзҳои таблиғотӣ",  "Паемҳо",  "Муттаҳидшавӣ",  "Фармоишҳои дастраскунӣ",  "Алмаато",  "Ном",  "Илова намудан",  "Амал",  "Навсозӣ",  "Ирсол",  "Бекор кардан",  "Шумо мутмаин ҳастед, ки мехоҳед ин вазифаро хориҷ кунед?",  "Бале",  "Не",  "Рақами пайгирӣ",  "Рақами пайгирии дохилӣ",  "Нархи воқеӣ",  "Нархи тахминӣ",  "Вазни воқеӣ",  "кг",  "Вазни ҳисобшуда",  "Кишвари пайдоиш",  "Навъи интиқол",  "Суроға",  "Ҳолати иҷроиш",  "Бор",  "Бақайдгирӣ",  "Баъдӣ",  "Тафтиш намудани рамз",  "Таъин намудани рамз",  "Рамзро тасдиқ кунед",  "Гирифтани SMS",  "Аввал рамзи тасдиқро қабул намоед",  "Тасдиқи рамз хато",  "Рақами телефон",  "Рамз",  "Формати рамзи нодуруст",  "Лутфан рақами телефонро ворид кунед",  "Лутфан SMS-ро ворид кунед",  "Суроғаҳои ман",  "Бастаҳои ман",  "Ба ҷои ман харед",  "Маълумоти шахсӣ",  "Навсозии рамз",  "Рамзи қаблӣ",  "Рамзи нав",  "Муваффақ",  "Маълумоти шахсӣ",  "Рӯйхати истифодабарандагон",  "Почтаи электронӣ",  "Илова кардани истифодабаранда",  "Ному насаб",  "ИИН",  "Рақами ҳуҷҷати тасдиқкунандаи шахсият",  "Мақоми ҳуҷҷатдиҳанда",  "Санаи додан",  "Мӯҳлати эътибор",  "Суроғаи интиқол",  "Шаҳр / Ноҳия",  "Кӯча",  "Хона",  "Индекси почта",  "Ҳуҷҷати тасдиқкунандаи шахсият",  "Тарафи рӯй",  "Тарафи баръакс",  "Имзо кашед",  "Е шартномаи имзошударо зеркашӣ кунед",  "Эзоҳ",  "Ҳуҷҷати замимашаванда бояд сифати хуб дошта бошад. Файли тасвир набояд аз 1 МБ зиед бошад.",  "Барои зеркашӣ файлро ба ин минтақа клик кунед е кашед",  "Фармоиши ман",  "Трек-код",  "Қабулкунанда",  "Номи бор",  "Арзиши эълоншуда",  "Сана",  "Арзиши интиқол",  "Кишвари фиристодан",  "Усули интиқол",  "Фармоиш",  "Маълумоти қабулкунанда",  "Кишвари интиқол",  "Усули интиқолдиҳӣ",  "Нарх",  "Миқдор",  "Арзиши умумӣ",  "Категория",  "Силоҳ ва маводи тарканда",  "Нӯшокиҳои спиртӣ",  "Спрейҳо ва аэрозолҳо",  "Доруворӣ бидуни таъиноти духтур",  "Элементҳои радиоактивӣ",  "Ҳайвонот ва наботот",  "ҲАМА ҲУҚУҚҲО ҲИФЗ ШУДААНД",  "Тамос",  "Дар бораи мо",  "Мағозаҳо",  "Ин чӣ гуна кор мекунад?",  "Тарофаҳо",  "Саволҳои зуд-зуд додашаванда",  "Ашеи манъшуда",  "Сиесати махфият",  "Вазн",  "Эъломия",  "Пардохт",  "Минтақаҳо",  "Кишвар",  "Суроғаи пурра",  "СУРОҒАИ МАН ДАР ЧИН БАРОИ ИНТИҚОЛИ АВТОМАТӢ",  "Бор илова намудан",  "Миқдорро ворид кунед", "Шумораи максималӣ",  "Чин",  "Интиқоли автоматӣ",  "Барои пешгирӣ кардани мушкилот зимни барасмиятдарории гумрукӣ, лутфан тавсифи муфассали номи молро ба забони русӣ нишон диҳед.",  "Баъдтар тасдиқ намудан",  "Тасдиқ намудан",  "Амалиет бомуваффақият гузашт",  "Истиноди ашеро фиристед, мо онро барои шумо мехарем ва дастрас мекунем!",  "Истинод ба бор",  "Шарҳи иловагӣ",  "Ое шумо ба харид розӣ ҳастед, агар ағйирёбии нарх то 7% бошад?",  "Андоза",  "Ранг",  "Нархи интиқол",  "Рамзҳои таблиғотӣ",  "Пардохт анҷом ёфт?",  "Анҷом",  "Ба анҷом нарасидааст",  "Тасвир бояд аз 3 МБ камтар бошад!",  "Тасвир бояд аз 2МБ хурдтар бошад!",  "Формати тасвир хато!",  "Дар бораи мо",  "Мағозаҳо",  "Чӣ гуна бо Чин кор кардан мумкин аст",  "OK",  "Ҳисобкунаки зуд",  "Илова кардани фармоиш",  "Арзиши интиқолро ҳисоб кунед",  "Маблағи умумии пардохт",  "Хона",  "Нусхабардорӣ дар як клик",  "Формати почтаи электронӣ хато",  "Пайгирии дархост",  "Шаблони шартнома",  "Формати файл хато!",  "Бозгашт ба саҳифаи асосӣ",  "Пардохт шудааст",  "Пардохт нашудааст",  "Вазъи пардохт",  "Ҷустуҷӯ",  "Ба фиристодан омода",  "Файл",  "Формати хато",  "Тавсиф",  "Дигар",  'Қабул намудани "ШАРТНОМАИ ОММАВӢ" ва "СОЗИШНОМА"',  "Қабул намудан",  "ШАРТНОМАИ ОММАВӢ",  "ва",  "СОЗИШНОМА",  "Ефт нашуд",  "Бастаро пайдо намудан",  "Ҳама",  "Маълумоти ҳуҷҷати тасдиқкунандаи шахсият",  "Забони русӣ", "Агар арзиши умумӣ аз 200 доллари ИМА зиед бошад, андози иловагӣ талаб карда мешавад",  "Сабаби нокомии санҷиш",  "Нав",  "Аввал маълумотро пур кунед",  "Боркашӣ шуда истодааст",  "Рӯйхати молҳо",  "Илова кардани трек - код",  "Таҳвил бо воситаи ҳавопаймо",  "Омода",  "Суратҳои пеш ва қафои ҳуҷҷати тасдиқкунандаи шахсияти худро зеркашӣ намоед",  "Ҳуҷҷати тасдиқкунандаи шахсият",  "Намуди ҳуҷҷати тасдиқкунандаи шахсият аз пеш",  "Намуди ҳуҷҷати тасдиқкунандаи шахсият аз қафо",  "Барои ба шумо расонидани мол аз давлати хориҷӣ, маълумоти ҳуҷҷати тасдиқкунандаи шахсияти худро ворид намоед.",  "Суроғаеро ворид кунед, ки аше бояд ба он расонида шавад",  "Имзо",  "Захира намудан",  "Таҳрир намудан",  "Хориҷ кардан",  "Ҳуҷҷатҳои фармоиш имзои электрониро талаб мекунанд.",  "Барои гирифтани мол бояд пардохт кард",  "Илова кардани эъломия",  "Барои интиқоли мол ба Қазоқистон бояд эъломия пур карда шавад",  "Маълумот",  "Шумо метавонед ба ин як трек код якчанд аше илова кунед.",  "Моли шумо ба анбори мо расид. Барои интиқоли он ба Қазоқистон бояд ба эъломия иловаҳо ворид карда шаванд. Дар он бояд ном, андоза ва нархи ашеи шумо инъикос карда шавад",  "Охири мундариҷа",  "Маълумот нест", "Пешина",  "Нархро ворид кунед",  "нархи максималӣ",  "нархи ҳадди аққал",  "миқдори максималӣ",  "миқдори ҳадди аққал",  "Бештар зеркашӣ кунед",  "Рӯйхати гирандагон",  "Иловаи қабулкунандаи нав",  "Филиалҳои мо",  "Пӯшида",  "Кушода",  "Рӯзи якшанбе истироҳат",  "Аз Чин ба филиалҳо",  "Филиал",  "Пардохти гурӯҳӣ",  "Шумо метавонед интиқолро барои якчанд бастаҳо якбора пардохт кунед",  "Интихоб намудан",  "Пардохт намудан",  "Дар баррасӣ",  "Санаи пешбинишуда",  "Филиалро интихоб кунед",  "Нархи мол",  "Филиали ман",  "Усули пардохтро интихоб кунед",  "Харита",  "Нусхабардорӣ карда шуд",  "Пардохт тавассути Kaspi",  "Маълумот дар бораи пардохт",  "Рақами фармоиш",  "Пардохти зуд дар барномаи Kaspi",  "Лутфан маҳдудиятҳои кортро тафтиш кунед",  "ШАРТНОМА",  "Розӣ",  "Дар раф",  "Шарҳ",  "Маълумоти иловагӣ",  "Лутфан суроғаи интиқолро ворид кунед",  "Расонидан то ба дар",  "Бо пур кардани ин маълумот, шумо метавонед хизматрасонии интиқолро фармоиш диҳед!",  "Дархост намудан",  "Хадамоти расонидан то дари хона",  "Таҳия шудааст",  "Омода шуда истодааст",  "Фиристода шуд",  "Таҳвил",  "Гирифта шуд",  "Маълумоти бештар",  "Рад карда шуд",  "Рақами телефони мобилӣ дар формати нодуруст нишон дода шудааст!", "Ба ман расонед",  "Дар филиали шумо ҳоло хизматрасонии 'Ба ман расонед'!" ,  "Фиристода нашудааст",  "Маблағро ворид кунед",  "Усули пуркуниро интихоб кунед",  "Пур кардан",  "Пур кардани ҳамен",  "Ҳамени ман",  "Таърихи ҳамен",  "Пур кардани тавозун",  "Пардохти бор",  "Амалиет",  "Бонусҳои ман",  "Дар давраи интихобшуда амалиет нест",  "Бозгашт",  "Бомуваффақият пардохта шуд",  "Функсияи мазкур насби версияи навро талаб мекунад, лутфан аввал онро навсозӣ кунед!",  "Шумо маблағи кофӣ надоред! Аввал ҳамени худро пур кунед.",  "Чеки пардохт",  "Интиқол бомуваффақият анҷом ефт!",  "Пур карда шуд, ба воситаи",  "Хизматрасонӣ",  "Тафсилоти хизматрасониро дидан",  "Тафсилоти хизматрасониро пинҳон намудан",  "Маблағ ба суратҳисоб баргардонида шуд",  "Интиқол байни ҳисобҳо",  "Ҳамен тоза карда шуд",  "Рақами пардохт",  "Бо тенге",  "Расид",  "Бонус ҳисоб карда шуд",  "Таърихи бонусҳо",  "Умумӣ",  "Бонус",  "Маълумоти шумо танҳо барои пайгирии фармоиш истифода мешавад. Ҳама маълумот ҳифз карда мешавад ва паҳн карда намешавад.",  "Аз ҳисоб бароварда мешаванд",  "Ба пардохт",  "Маълумоти зарурӣ",  "Хизматрасонии 'Ба ман дастрас намоед' дар филиали шумо дастрас нест",  "Арзиши ба ман дастрас намудан",  "Арзиши хизматрасонӣ",  "Ба WhatsApp нависед",  "Молҳои шумо ба анбори хориҷии JAŃA POST меоянд. Мунтазир бошед, то онро қабул кунанд.",  "Фаҳмо",  "Ташаккур барои фикру мулоҳизаҳои шумо!",  "Мубодила",  "Ое шумо ҷавобро муфид донистед?",  "Лутфан сабабашро нишон диҳед",  "Пешниҳоди беҳтар кардани ҷавобро тавсиф кунед",  "Ман ба савол ҷавоби пурра нагирифтам",  "Ҷавоб кӯмак накард",  "Пешниҳоди ман",  "Роҳнамо",  "Ҳоло ҳам мушкилотро ҳал карда наметавонед?",  "Омор",  "Шумораи фармоишҳо",  "Вазни фармоиш",  "Бозпас гардонида шуд",  "Интиқол",  "JPID қабулкунанда",  "Паем",  "Паем ба қабулкунанда",  "Тағйир додани қабулкунанда",  "Маълумоти шахсиро ворид кунед",  "Маълумоти шахсӣ аз санҷиш гузашта истодааст",  "Маълумоти шахсӣ аз санҷиш нагузашт",  "Маълумоти шахсӣ санҷида шуд",  "Майдончаи ҳатмӣ",  "Арзиши ҳадди аққал",  "Арзиши максималӣ",  "Маблағ кофӣ нест",  "Корти дигарро нишон диҳед",  "Интиқол нагузашт!",  "Бори дигар кӯшиш кунед",  "Саволҳои зуд-зуд додашаванда",  "Тавозун",  "Ҳисоби шумо холӣ аст!",  "Барои фармоиш тавассути барнома, ҳисоби худро пур кунед",  "Таърих",  "Даъват намудан",  "Харидан",  "Таърих нест",  "Филтр",  "Давра",  "Як",  "Се",  "Нисф",  "Ним сол",  "Ҳафта",  "Сол",  "Моҳ",  "Солҳо",  "Моҳҳо",  "Маълумот дар бораи фармоиш",  "Фармоиши шумо ба ин филиал расонида мешавад",  "Паем нест",  "Арзебӣ",  "Шиноснома",  "Навъи ҳуҷҷатро интихоб кунед",  "Акси шиносномаро зеркашӣ кунед",  "Филиалҳои наздиктарин",  "Филиал бомуваффақият нав карда шуд",  "Филиали нав кушода шуд",  "Агар мақоми мол маркази ҷобаҷогузорӣ, рафи шӯъба қайд шуда бошад, шумо молро аз шӯъбаи пешина мегиред. Аз шӯъбаи навтаъсис шумо метавонед танҳо ашёеро гиред, ки ба маркази навъбандӣ нарасидааст.",  "Бале, ман ин филиалро интихоб мекунам", "Дастраскунии ройгон",  "Расонидан ба хона",  "Идома додан", "Лутфан барои истифодаи замимаи Jańa Post маълумоти шахсии худро ворид кунед. Маълумоти шахсии шумо барои барасмиятдарории гумрукӣ талаб карда мешавад ва танҳо аз ҷониби мо нигоҳ дошта мешавад.",  "Имзои электронӣ. Барои тасдиқи маълумотҳои шахсӣ, шумо бояд имзои электронии худро ворид кунед", "Забонро интихоб намоед",  "Лутфан суроғаи истиқоматро пур намоед",  "Шаҳр/минтақаро интихоб кунед",  "Харита",  "Рӯйхат",  "Қоидаҳои асосӣ",  "Дар харита дидан",  "Боррасон",  "Аз рӯи интиқол",  "Аз рӯи интизориҳо",  "Оғоз намудани кор",  "Анҷом додани кор",  "Рамзи тасдиқ",  "Штрих-код",  "Санҷиш бомуваффақият гузашт",  "Рамзро дубора фиристодан",  "Фармоиши фавқулодда",  "Сабаби ҳолати фавқулодда",  "Иҷозат дода шуд",  "Рад карда шуд",  "Бомуваффақият иҷро шуд",  "Шумо дар сурати гум шудани фармоиш масъулияти пурраро ба дӯш мегиред",  "Сабаби ҳолати фавқулоддаро нишон додан лозим аст.",  "Зеро",  "Гирифтани фармоиш",  "Фармоишҳое, ки бояд ба филиал баргардонида шаванд",  "Саривақт дастрас накард",  "Лутфан баҳо диҳед!",  "Ташаккур барои эзоҳи шумо!",  "Мо барои шумо чӣ беҳтар карда метавонем??",  "Фикри шумо",  "Сабабро интихоб кунед",  "Ирсоли рамзи тасдиқ ба муштарӣ",  "Барномаҳоро арзёбӣ намоед",  "Интернет нест",  "Корт илова кунед",  "Мо маълумоти кортро нигоҳ намедорем. Амниятро Freedom кафолат медиҳад",  "Пардохт дар коркард",  "Маблағ дар давоми якчанд дақиқа ба корт ворид карда мешавад",  "Маълумот оиди корт нобуд карда шавад?",  "Корти бонкии мазкур дигар дар рӯйхати кортҳои барои пардохт дастрас, инъикос намегардад."]

const res = {

}

langKeys.forEach((key, i) => {
    res[key] = langTg[i]
})

console.log(res)